//NOT USED YET
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

//HOMES ACTION-TYPES OWNER
export const NEW_HOME = "NEW_HOME";
export const UPDATE_HOME = "UPDATE_HOME";
export const DELETE_HOME = "DELETE_HOME";
export const GET_HOMES = "GET_HOMES";
export const GET_MY_HOMES = "GET_MY_HOMES";
export const GET_HOMES_BY_CHART = "GET_HOMES_BY_CHART";


//HOME ACTION-TYPES TENANT LANDING PAGE
export const FEATURED_ROOMS = "FEATURED_ROOMS";
export const STATISTICS = "STATISTICS";
export const SEARCH = "SEARCH";
export const GET_ROOMS = "GET_ROOMS";
export const ROOM_INTERESTED= 'ROOM_INTERESTED'
export const TENANT_ROOMS= 'TENANT_ROOMS'
export const REMOVE_TENANT_ROOMS= 'REMOVE_TENANT_ROOMS'
export const TENANT_BOOKED_ROOMS= 'TENANT_BOOKED_ROOMS'




//NOT USED YET
export const GET_HOME_BY_ID = "GET_HOME_BY_ID";
export const GET_HOME_BY_CITY = "GET_HOME_BY_CITY";
export const GET_HOME_BY_RADIUS = "GET_HOME_BY_CITY";


//FILTER AND SEARCH
export const ROOMS_BY_CITY = "ROOMS_BY_CITY";
export const ROOMS_BY_WIFI = "ROOMS_BY_WIFI";
export const ROOMS_BY_MESS = "ROOMS_BY_MESS";
export const ROOMS_BY_CAPACITY = "ROOMS_BY_CAPACITY";
export const ROOMS_BY_SIZE = "ROOMS_BY_SIZE";
export const ROOMS_BY_PRICE = "ROOMS_BY_PRICE";
export const ROOMS_BY_FUZZY = "ROOMS_BY_FUZZY";
export const ROOMS_BY_NEED = "ROOMS_BY_NEED";
export const ROOMS_BY_ZIPCODE_RADIUS= "ROOMS_BY_ZIPCODE_RADIUS";






export const GET_ROOM_DETAILS = "GET_ROOM_DETAILS";


// GET_HOME_BY_ID,GET_HOME_BY_CITY,UPDATE_HOME,DELETE_HOME,GET_HOMES
